name: dynopy
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy
    - matplotlib
    - h5py
    - scikit-learn
    - mdanalysis 
    - jupyterlab
    - argparse
    - six
    - tqdm
    - scipy
    - igraph
